algo = input('Digite algo: ')
print('O tipo do que foi digitado é ', type(algo))
print('É alpha? ',algo.isalpha())
print('É numérico? ', algo.isnumeric())
print('É alphanumérico? ', algo.isalnum())
print('Está todo em Maiúsculo? ', algo.isupper())
print('Está todo em Minúsculo? ', algo.islower())
print('Contém espaços?', algo.isspace())
print('É um título? ', algo.istitle()) 
print('É printável? ', algo.isprintable())
print('É um indenficador? ', algo.isidentifier())
print('É decimal? ', algo.isdecimal())
print('É dígito? ', algo.isdigit())
print(algo.isascii()) #Não sei o que é isso
